### ISSUE TITLE
Hosting the .DLL?

### ISSUE THREAD

**Issue by NTULINUX** [kcat/dsoal#10]
Hi,

If it's OK, I'd like to host a release build of the generated dinput8.dll on a Github fork of this project for those who don't want to compile anything. Is there a reason there isn't a .dll file in the releases page? I never built anything for Windows before but I was able to figure it out pretty quick. I had to download CMake from the official website as I don't think it was part of Visual Studio. If it's because of a licensing problem, I won't do it.

Thanks!

**Comment by kcat** [comment]
You mean `dsound.dll`? There's no `dinput8.dll` here. But sure, go ahead. Just be aware that it also needs an `aldrv-dsoal.dll` (a renamed openal soft dll), to work. Licensing shouldn't be an issue, both are available under the LGPL 2.1 or later.

**Comment by NTULINUX** [comment]
Yes, dsound is what I meant, sorry. So to make sure I have this right...

1.) To make sure games recognize soft_oal.dll, copy bin/win32/soft_oal.dll as OpenAL32.dll into 32-bit game directory

2.) Inside game directory, copy recently copied OpenAL32.dll file to dsoal-aldrv.dll so both instances of the same file exist, with two different names. This way games load OpenAL32.dll from OpenAL Soft and not the Creative Labs one, and have the second instance of the same file there so dsoal can find it.

3.) Copy recently compiled dsound.dll (built from dsoal git tree) into game directory, so game loads dsound.dll from dsoal instead of the one shipped with the game or DirectX.

**Comment by kcat** [comment]
> 1.) To make sure games recognize soft_oal.dll, copy bin/win32/soft_oal.dll as OpenAL32.dll into 32-bit game directory

There's no need to have an OpenAL32.dll if the game uses DSound. You can just copy bin/win32/soft_oal.dll as dsoal-aldrv.dll into the 32-bit game directory without OpenAL32.dll.

> 3.) Copy recently compiled dsound.dll (built from dsoal git tree) into game directory, so game loads dsound.dll from dsoal instead of the one shipped with the game or DirectX.

Correct.

**Comment by NTULINUX** [comment]
Thank you kcat for your help and hard work on dsoal!

I have the DLL files hosted on my fork:

https://github.com/NTULINUX/dsoal/releases

I wish I knew about this project sooner, I invested in Creative cards and used ALchemy when I could have just used this. Creative cards have terrible Linux support and even Windows driver problems.

Thanks again, you rock!
