### ISSUE TITLE
Muffled Sound

### ISSUE THREAD

**Issue by PlayNeth** [kcat/dsoal#108]
In Need for Speed High Stakes the sound output gets really muffled when going through DSOAL, and I'm not entirely sure if this is normal behavior or not due to the EAX effects. Could you please shine some light on this? Here's a comparison:

DSOAL
https://github.com/user-attachments/assets/3ff133ad-e51d-4768-a13f-7865ee6e82b2

No DSOAL
https://github.com/user-attachments/assets/5dbf790a-ec96-427a-8909-447671760f36

**Comment by mirh** [comment]
https://www.vogons.org/viewtopic.php?t=94106&start=20
Interestingly enough, it is argued that even Creative's cards themselves were subpar once they went from 9x to XP.

Anyhow dsoal development is kinda on pause atm while openal-soft is getting all the different kinds of bells and whistles.. So, I don't know, maybe you could experiment a bit with some [older](https://www.nexusmods.com/newvegas/mods/65094/?tab=files&category=archived) [version](http://vaporeon.io/hosted/dsoal-builds/old/) to see if you can get some better bang for the buck.

**Comment by ThreeDeeJay** [comment]
Same as https://github.com/kcat/openal-soft/issues/1089#issuecomment-2563966891 ?
Try disabling HRTF in alsoft.ini by setting:
```
stereo-encoding=basic
```

You'd still get EAX (reverb) but no 3D audio (like hearing cars chasing you as if they're actually behind you, not inside your head), which is what HRTF does at the expense of slight "muffling".

**Comment by PlayNeth** [comment]
> Same as [kcat/openal-soft#1089 (comment)](https://github.com/kcat/openal-soft/issues/1089#issuecomment-2563966891) ? Try disabling HRTF in alsoft.ini by setting:
> 
> ```
> stereo-encoding=basic
> ```
> 
> You'd still get EAX (reverb) but no 3D audio (like hearing cars chasing you as if they're actually behind you, not inside your head), which is what HRTF does at the expense of slight "muffling".

Nope. Even with it disabled it still sounds muffled. I've tried every possible filter combination as well and they don't sound much different from each other.

**Comment by ThreeDeeJay** [comment]
What about
```
[general]
resampler=spline
```

**Comment by PlayNeth** [comment]
> What about
> 
> ```
> [general]
> resampler=spline
> ```

Yeah using your fork of DSOAL without HRTF + spline seems to have solved it! Thanks!

**Comment by mirh** [comment]
It should be already fixed in the last oalsoft builds.
