### ISSUE TITLE
Current git master crashes "Halo PC" when built with MinGW-w64

### ISSUE THREAD

**Issue by Vaporeon** [kcat/dsoal#12]
Instant crash on game startup
It broke some time after 9d3ede6d9fc48c80a0554f2adcc5ecf5ac42e277

Side issue: openal-soft 1.20.0 hangs on exit with the above commit so the process stays alive, this seems to be with anything that uses dsound-openal. 1.19.1 works fine. Not sure where the bug is there.

**Comment by kcat** [comment]
The hang at exit may have been this (now fixed) issue: https://github.com/kcat/openal-soft/issues/378

As for the crash, are you able to get a backtrace? Or do a git bisect to find which commit it started with?

**Comment by donizettilorenzo** [comment]
LOL, I was about to open the same ticket :-p

Hi Vaporeon, your old dll is still OK!

**Comment by Vaporeon** [comment]
Broken as of 09a2903b02cf929ee9a84b5c79aff667e4537c2b
The last working build I have is 9d3ede6d9fc48c80a0554f2adcc5ecf5ac42e277 however I no longer have a mingw version that can compile it.

**Comment by Vaporeon** [comment]
This seems to no longer be an issue, current git master (f2d74d7c29888dba367b42556a9db91e5c5dbf66) works.
