### ISSUE TITLE
Wrong export ordinals cause games to call wrong function (eg. FalloutNV)

### ISSUE THREAD

**Issue by emoose** [kcat/dsoal#17]
Took a little bit to debug, but it seems games that have hardcoded import ordinals will import the function at that ordinal without checking the name.

eg. FalloutNV.exe has DirectSoundCreate8 hardcoded to ordinal 11 (Windows dsound.dll also has DirectSoundCreate8 at ordinal 11) but new dsoal has DllCanUnloadNow at that ordinal instead, with DirectSoundCreate8 at ordinal 9 instead.

Using DSOAL_LOGLEVEL=3 would show
```3544:fixme:dsound:DSOAL_DllCanUnloadNow (void): stub```
in the log file, but no traces from DirectSoundCreate8, seemed like it wasn't being called at all, this led to NV crashing on startup as some return pointer from DirectSoundCreate8 wasn't being set.

After some digging I noticed NV had that hardcoded ordinal, and updated msvc.def to put DirectSoundCreate8 there, and now FNV runs fine without crashing, here's updated msvc.def which should match Windows dsound.dll (I'd guess the other def files would also need similar changes) https://gist.github.com/emoose/225a45fd1ad92fc7eea5d1e48ab76adf

**Comment by kcat** [comment]
Fixed with commit b0bea6ed3fa7335c8b71f8b8bbcbe29308820d8d.
