### ISSUE TITLE
(Fixed) Does not work on 64 bit game.

### ISSUE THREAD

**Issue by Galenmacil** [kcat/dsoal#21]
It would seem a 64 bit dsound.dll is required... Is that doable?

**Comment by kcat** [comment]
DSOAL should be buildable as a 64-bit DLL. This isn't well-tested since there's not many 64-bit apps that use DirectSound (XP 64-bit wasn't widely used, and Vista killed accelerated DirectSound and deprecated it in favor of other APIs), so if there's a particular bug, it will need to be reported.

**Comment by Galenmacil** [comment]
I tried to build the project, in 64 bit, using CMake 3.19.0-rc1 without success. I installed "Microsoft Visual Studio 2019 Community" as well.

CMake-GUI Result when attempting to configure or build:

![CMake](https://user-images.githubusercontent.com/19394274/96401495-7d07c480-11a1-11eb-935f-f0700fb7776d.png)

VS2019 Component Installed:
![VS2019](https://user-images.githubusercontent.com/19394274/96401500-81cc7880-11a1-11eb-9049-8261a117a4dc.png)

I am just asking for a nudge in the right direction... What am I missing?

I am quite new to this. I do have some C and Assembler programming experience but it date back to the mid 90's so that hardly even count. haha.

**Comment by Galenmacil** [comment]
Posting an update to that 64 bit build proposition. After a bit of fiddling around with the Visual Studio 2019 Installer, I realized i needed to have the package called "Windows 10 SDK" installed as well. I was unable to build the DSound.dll with CMake (The process would complete, but I could not find the file anywhere in the folder it was supposed to land) but I managed to generate one correctly with the VS2019 IDE.

I used "Visual Studio 16" as the generator. Architecture was set to "x64" and build type to "Release".

Now, the game I needed this for is "Grim Dawn". The game as a 64 bit build since about last year and it run much smoother than the 32 bit one. A few member of the crew behind "Crate", the developer, comes from the team that made "Titan Quest", which is a DirectSound title supported by creative ALchemy. So Grim Dawn inherited that game sound system DNA so to speak.

Why I needed to install 5.9 GB worth of stuff to compile a ~217k dynamic link library is beyond me but, hey, it worked so...

**Comment by TheThunderGuyS** [comment]
I am able to compile it just fine with MinGW-w64 (GCC 8.1.0) under Windows. Must've been MSVC being weird. You should also probably close this issue if it's resolved for you.

**Comment by ThreeDeeJay** [comment]
For anyone still looking but lacks the knowledge of source compilation, 64-bit DSOAL gets automatically compiled and uploaded here:
https://ci.appveyor.com/project/ChrisRobinson/dsoal
Select x64 job > Artifacts > dsoal.zip
e.g. at the time of writing, this is the current one: https://ci.appveyor.com/api/buildjobs/w41j6abld66mn654/artifacts/dsoal.zip
