### ISSUE TITLE
Log file errors when using latest artifact with SimCity 3000 Unlimited

### ISSUE THREAD

**Issue by sjkorvin** [kcat/dsoal#42]
Hello. I had been using Creative ALchemy with my Sound Blaster AE-9 sound card. I bought a Steelseries Arctis Pro Wireless headset thinking that I could use an optical audio cable from the back of the sound card to the Steelseries control box. The optical audio input on the control box is only present for using the headset with a PlayStation 4. You must use USB audio with a PC. I'm keeping the AE-9 because its control box has an XLR connector for my microphone.

Because of all this, I looked into DSOAL. I'm running Windows 11 x64. I'm using the latest DSOAL Win32 artifact from November 19th, 2021 and my Win32 dsoal-aldrv.dll file was downloaded from the OpenAL Soft website. Its version is 1.21.1.0.

When setting ```DSOAL_LOGLEVEL=1```, I end up with the following errors in my ```dsoal_log.txt``` file after running one of the pre-made cities in SimCity 3000 Unlimited from GOG for a few minutes:

```
4c20:err:dsound:DSBuffer_Initialize Panning for multi-channel buffers is not supported
663c:fixme:dsound:DS8_CreateSoundBuffer Buffers with 3D and panning control ignore panning
```
I would please like to ask if this means that there are problems and if there are, if there would be a way to fix them. Thank you very much.

**Comment by mirh** [comment]
There are def problems, and missing features. Nothing that couldn't be eventually fixed. 
It just takes time, which at the moment no competent dev has in their hands.

**Comment by sjkorvin** [comment]
Thank you. I'll plug my headset into the Sound Blaster AE-9 control box in the meantime. Also, I will close this issue.
