### ISSUE TITLE
James Bond 007: NightFire - Broken virtual surround or virtual stereo

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/dsoal#44]
According to some sources ([1](https://www.pcgamingwiki.com/wiki/James_Bond_007:_Nightfire#Audio),[2](https://www.mobygames.com/game/007-nightfire_/techinfo)), this game has DirectSound3D + EAX, while others ([3](https://web.archive.org/web/20130702030043/http://connect.creativelabs.com:80/alchemy/Lists/Games/AllItems.aspx),[4](https://docs.google.com/document/d/1SyOw7D0H2ecGxzPsCFEFKwupU8LuazUrlkI-gVTpyhc/edit)) claim it's just EAX (?)
Perhaps there's a way to force DS3D but at least on my end, I'm not sure any of them are working:
- With the latest DSOAL + OpenAL Soft 1.21.1, it's just virtualized stereo: https://youtu.be/pK4FlYAmI_w - [Log](https://github.com/kcat/dsoal/files/8172021/DSOAL.log)
- With the [XP fork of DSOAL and OpenAL Soft](https://github.com/pachuco/dsoal-XP/tree/master/release), it's virtual surround but rear channels transition into the front channels (or just front center?), so I can hear stuff behind on my left or my right, but stuff behind me sounds like it's in front of me: https://youtu.be/loUOcVmH7to - [Log](https://github.com/kcat/dsoal/files/8172024/DSOAL-XP.log)
- With the latest Creative ALchemy, it's just stereo without HRTF: https://youtu.be/91YGz1_S0i4 - [Log](https://github.com/kcat/dsoal/files/8172026/ALchemy.log)
- On Windows XP with hardware CMSS-3D, it's also just regular stereo without HRTF, unless I enable CMSS-3D manually via the Creative Control Panel in which case it's virtual stereo even if the windows speaker config is 4.0/5.1 and the game's supposed to auto-detect it according to PCGW. And from the API calls, it seems to be using WinMM instead of DirectSound(?): https://i.imgur.com/OINfRmw.png
- Even tried [MetaAudio](https://github.com/LAGonauta/MetaAudio) since it runs on the GoldSrc engine, but it just fails to run with an [error](https://i.imgur.com/KqDdBaB.jpeg) and when copying over hl1 files I get [this](https://cdn.discordapp.com/attachments/547441642555310092/843636038856343613/unknown.png) and if I replace the client.dll from valve\cl_dlls into bond\cl_dlls, metaaudio works but it's just half life even tho I passed -game bond as the argument to the shortcut
Not surprised since the engine has been [heavily modified](https://developer.valvesoftware.com/wiki/James_Bond_007:_Nightfire).
- And lastly, the game just outputs stereo with or without IndirectSound, at least on my end, so using virtual surround software like HeSuVi will just result in virtualized stereo: https://youtu.be/hB0sN-J1MeE

**Comment by mirh** [comment]
> According to some sources (1,2), this game has DirectSound3D + EAX, while others (3,4) claim it's just EAX (?)

And how is that a difference in any shape or form?

**Comment by ThreeDeeJay** [comment]
@mirh Hence the question mark lol
Guess they meant [EAX without (working) DirectSound's 3D HRTF/positional audio](https://i.imgur.com/rKb0ifG.jpeg).

**Comment by mirh** [comment]
You are really assuming/reading too much from those words. 
Unless it's the literal engineer that coded the thing giving an interview to a specialized magazine, all those terms shouldn't be interpreted very technically (in fact, to this day, I myself still haven't found a comprehensive source detailing how DS3D is different from DS, and the "hardware path"). 

Anyhow, I'm seeing the game had a demo and a patch. Maybe you can experiment further with them.

**Comment by ThreeDeeJay** [comment]
@mirh Yeah, I was just paraphrasing sources that I take with a grain of salt till proven.
I know 3D positional audio like in [RightMark 3D sound where there are calls updating 3D coordinates](https://i.imgur.com/A2jjaXe.jpeg) isn't always guaranteed by DS3D. Some games use DS3D but lack verticality (like [NFS: Hot pursuit 2 and 3](https://github.com/kcat/dsoal/issues/43#issuecomment-1033098323)) and others seem to just use DS3D buffers as virtual speakers like [early Half-Life 2](https://cdn.discordapp.com/attachments/757082238327193722/946046106758955068/unknown.png). Also EAX isn't exclusive to DS3D since some OpenAL games like [Bioshock](https://youtu.be/vq6rda4oJac) use it, but don't use DirectSound3D for 3D positional audio, only surround if anything.

Semantics aside, I tried the [Nightfire demo](https://community.pcgamingwiki.com/files/file/324-james-bond-007-nightfire-demo/) and oddly [the audio behaves differently than in the full game on WinXP](https://i.imgur.com/kV1YjP9.gif).
In-game audio bypasses CMSS-3D HRTF *while* it's virtualizing music playing in WMP, whereas the full game can be virtualized (although just stereo). Not sure if that means anything useful but thought it was peculiar. On windows 10 however, both versions behave the same way: latest DSOAL and v1.1 result in virtual stereo, while with DSOAL-XP fork (ironically) I get the best* results with virtual surround (although broken rear positionality like I mentioned in the OP). DSOAL-XP's [last upstream commit](https://github.com/pachuco/dsoal-XP/commit/f2d74d7c29888dba367b42556a9db91e5c5dbf66) outputs virtual stereo so perhaps the answer lies in the [fork's changes](https://github.com/pachuco/dsoal-XP/commits/master). 👀

As for the official 1.1 update, I get the same results as 1.0 on XP but it wouldn't run on 10. Conversely, the unofficial patch v5.91 wouldn't run on XP but on Win10 I get the same results as with the demo/full game.

Also I didn't find any DS3D/EAX ini settings or console commands, but I still can't help but think I'm missing something.
But anyway, these are just my observations. Perhaps other people would have better luck.
Hopefully kcat gets a chance to look at the logs and get an idea of what's going on. 🤞

**Comment by colistro123** [comment]
Nightfire's GoldSrc engine was modified so much by Gearbox to the point where trying to implement anything such as Metamod or even AMXMODX turned into a pain. It's pretty much impossible for anything such as MetaAudio or EAX to work out of the box, for instance I believe Nightfire doesn't support EAX. Most of these mods, for example Metamod, rely on hooking vtables and iirc, back in 2014, it was problematic to a certain point, to make Metamod work with Nightfire since the vtables Metamod was trying to hook where modified by Gearbox and they didn't match, resulting in crashes. It was actually [@click4dylan](https://github.com/click4dylan) who actually got this done and it involved a lot of manual labor such as comparing game VMTs to the ones being hooked by Metamod, the fix was patching certain [VMTs](https://github.com/colistro123/Nightfire-iniMod/blob/master/engine.cpp#L75) lol. I expect trying to make something such as MetaAudio work be almost the same.

There's a [Discord](https://discord.gg/y2HUNsKueU) server you can join if you have questions related to the original Nightfire game :-)

**Comment by ThreeDeeJay** [comment]
@colistro123 [So you're telling me there's a chance...](https://youtu.be/Ms7KbMfXHp8)
fr tho, now that you know what to patch to make MetaHook work, would you or [click4dylan](https://github.com/click4dylan) be willing to patch MetaAudio? 👀 
If the game really lacked EAX all along, perhaps MetaAudio could make up for it with the GoldSrc/Steam occlusion 🤔

**Comment by ThreeDeeJay** [comment]
Looks like [Nightfire is getting MetaAudio](https://github.com/click4dylan/Nightfire_SDK) 🎉

**Comment by ThreeDeeJay** [comment]
A couple updates on MetaAudio:
Initial implementation: https://youtu.be/5ay5DxvqQxU
Reverb + transition: https://i.imgur.com/oLK4Tka.mp4
Steam Audio Occluder: https://i.imgur.com/jKDZ7eu.mp4
This was all done by [click4dylan](https://github.com/click4dylan), who's gonna add it to the [unofficial patch](http://nightfirepc.com/), so I guess there's no point in trying to fix DSOAL support in this game so I'll go ahead and close this issue.

**Comment by Scr34mik** [comment]
Hello, id like to report having the same issue as OP with dsoal v1.3a and original half life v1.0.0.5 (build 742).
Even if i set "channels=stereo" the game still using back channels as front ones:
![image](https://github.com/kcat/dsoal/assets/10966059/7adc3036-e4dc-49cc-9806-66c920e42a0e)

Q: You can patch the game isnt it ? 
A: well yes. And thats the point. Im running original version with dgvoodoo to get the most out of it

Q: What about later version of DSOAL ?
A: v1.4 has weird sound corruption.

In general, i'd like to just leave this feedback here, on a "FYI" basis. What you do with it, is up to you.

**Comment by ThreeDeeJay** [comment]
Or one of these 👀 
https://github.com/ThreeDeeJay/dsoal/releases/latest (last stable DSOAL with last stable OpenAL Soft)
https://github.com/ThreeDeeJay/dsoal/releases/tag/latest (latest DSOAL commit with latest OpenAL Soft commit)

**Comment by mirh** [comment]
I mean, if channel redirection doesn't work that's still kinda beside the point.. something was broken here. 
On the other hand, it's kinda pointless to report against a 4 years (and ~60 commits) old version. 
If any a new ticket about sound corruption (if still present in the last git, given I'm fairly sure it ain't supposed to happen even with the most ancient ass MSS) could have been have been opened, noting on the other way around the old behaviour.
