### ISSUE TITLE
EAX not working even with latest version of DSOAL & OpenAL-Soft

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/dsoal#45]
I compiled the latest verion of DSOAL and OpenAL-Soft put everything in the appropriate directories however games with EAX support won't allow EAX to be selected. I ran the ALcaps viewer and it shows OpenAL-soft has EAX support. I can however select the basic Windows Hardware 3D audio in older games. Tested multiple EAX enabled games from EAX 1-EAX 4 support.

**Comment by Kappa971** [comment]
In the game folder you need dsound.dll (the 32-bit dll from DSOAL, as the game is probably 32-bit) and the OpenAL Soft dll renamed to dsoal-aldrv.dll. You can copy dsoal-aldrv.dll (32 bit) to C:\Windows\SysWOW64 in such a way that all games will use it, without having to copy the dll to each game folder. DO NOT do this with DSOAL (dsound.dll), otherwise you will overwrite the original Windows dll and risk breaking the system. You need to copy the DSOAL dsound.dll to the folder of every game that uses DirectSound.
Use Windows 10 or 11.
Add these registry keys: [CURRENT_USER.-.Add.dsound.zip](https://github.com/kcat/dsoal/files/8238662/CURRENT_USER.-.Add.dsound.zip)

I'm not a developer so if that didn't solve the problem, you just have to wait for a response from the developer.

**Comment by Jenavieve-Rose** [comment]
> In the game folder you need dsound.dll (the 32-bit DSOAL dll as the game is probably 32-bit) and the OpenAL Soft dll (32 bit) renamed to dsoal-aldrv.dll. You can copy dsoal-aldrv.dll to C:\Windows\SysWOW64 in such a way that all games will use it, without having to copy the dll to each game folder. DO NOT do this with dsound.dll (DSOAL), otherwise you will overwrite the original Windows dll and risk breaking the system. You need to copy the DSOAL dsound.dll to the folder, containing the game executable, of every game that uses DirectSound. Use Windows 10 or 11. Add these registry keys: [CURRENT_USER.-.Add.dsound.zip](https://github.com/kcat/dsoal/files/8238662/CURRENT_USER.-.Add.dsound.zip)
> 
> I'm not a developer so if that didn't solve the problem, you just have to wait for a response from the developer.

I mean yes I am doing this following the directions to a T. I have used both these before with no issue. This seems to be a recent issue I have experienced with the newer DLL.

**Comment by hanfling** [comment]
A couple of days ago I build both myself and tried to use them with EAGLE 2.0, which started, but had no sound output. I didn't add any of the the registry keys.

**Comment by kcat** [comment]
> games with EAX support won't allow EAX to be selected.

What games did you try? Can you provide a trace log from trying to use and select EAX in one of the apps? Set the `DSOAL_LOGLEVEL` environment variables to `3` and `DSOAL_LOGFILE` to `c:\some\path\dsoal.log`, then run the app and try to enable EAX. The log file will show what it tried to do, which can help indicate why EAX won't work.

**Comment by Jenavieve-Rose** [comment]
> > games with EAX support won't allow EAX to be selected.
> 
> What games did you try? Can you provide a trace log from trying to use and select EAX in one of the apps? Set the `DSOAL_LOGLEVEL` environment variables to `3` and `DSOAL_LOGFILE` to `c:\some\path\dsoal.log`, then run the app and try to enable EAX. The log file will show what it tried to do, which can help indicate why EAX won't work.
> 
> > A couple of days ago I build both myself and tried to use them with EAGLE 2.0, which started, but had no sound output. I didn't add any of the the registry keys.
> 
> A trace log from that would help too.
[dsoal.log](https://github.com/kcat/dsoal/files/8239794/dsoal.log)
SO, I was testing FEAR and when I run the game EAX 2.0 and HD is greyed out I also tried Star Wars THe Phantom Menace same results. Here is the log for FEAR. However I already kind of figured it out. I had an alsoft.ini in there as well and that seemed to have been causing the problem. As soon as I deleted that file everything was working. You can take a look at the log to see if it tells you why. Either way I just won't use the ini thanks for your time.

**Comment by Jenavieve-Rose** [comment]
Is there any way to adjust the reverb effect as it is way too high in a lot of games now that I got it working?

**Comment by Kappa971** [comment]
> Is there any way to adjust the reverb effect as it is way too high in a lot of games now that I got it working?
> 
> thanks for your time.

In alsoft.ini adjust the following setting:
`[reverb]`
`boost = 0`

I noticed that, for example in GTA 3, reverb is now also used in radio stations. There is probably still something to fix.

**Comment by mirh** [comment]
F.E.A.R. may or may not require XP compatibility #11

**Comment by Jenavieve-Rose** [comment]
> > Is there any way to adjust the reverb effect as it is way too high in a lot of games now that I got it working?
> > thanks for your time.
> 
> In alsoft.ini adjust the following setting: `[reverb]` `boost = 0`
> 
> ex. `boost = -6`
> 
> I noticed that, for example in GTA 3, reverb is now also used in radio stations. There is probably still something to fix.
> 
> EDIT Lambert's voice in Splinter Cell now also has reverb. I think it shouldn't be there.

Okay well that is part of the problem if I have the ini file in the folder it disables EAX Effects altogether and doesn't allow you to select EAX. So, I can't change the reverb with it.

**Comment by mirh** [comment]
Maybe try to understand which option is responsible?

**Comment by Jenavieve-Rose** [comment]
> Maybe try to understand which option is responsible

> Maybe try to understand which option is responsible?

So, I decided to just leave in where it points to the driver and the reverb setting and it works fine. So, one of the other options was majorly screwing with it. It works as long as the only parameters specified is the driver and reverb levels. I will just use OpenAL-Soft configurator for anything else.

**Comment by kcat** [comment]
> Setting reverb boost to 0 seems to be like a default reverb setting it's still there just not very high. Setting it to -6 seems to cut the effect in half, but what setting removes it entirely?

Setting the `default-reverb` option would disable EAX. The `excludefx` option can also be used to disable EAX Reverb, which would also prevent it from working.

**Comment by Jenavieve-Rose** [comment]
> > Setting reverb boost to 0 seems to be like a default reverb setting it's still there just not very high. Setting it to -6 seems to cut the effect in half, but what setting removes it entirely?
> 
> Setting the `default-reverb` option would disable EAX. The `excludefx` option can also be used to disable EAX Reverb, which would also prevent it from working.

Sorry to sound stupid but I am not sure how to specify `default-reverb` option or `excludefx`. If I put in the alsoft.ini default=-reverb nothing seems to happen still have reverb. Same if I just do default-reverb. Also, I am not sure how to use excludefx command. Thank you for your time and my apologies.

**Comment by Kappa971** [comment]
> Sorry to sound stupid but I am not sure how to specify `default-reverb` option or `excludefx`. If I put in the alsoft.ini default=-reverb nothing seems to happen still have reverb. Same if I just do default-reverb. Also, I am not sure how to use excludefx command. Thank you for your time and my apologies.

Setting `boost = -12`, the reverb is probably so minimal that it isn't audible. Also EAX without reverb isn't EAX 😁

**Comment by Jenavieve-Rose** [comment]
> > Sorry to sound stupid but I am not sure how to specify `default-reverb` option or `excludefx`. If I put in the alsoft.ini default=-reverb nothing seems to happen still have reverb. Same if I just do default-reverb. Also, I am not sure how to use excludefx command. Thank you for your time and my apologies.
> 
> Setting `boost = -12`, the reverb is probably so minimal that it isn't audible. Also EAX without reverb isn't EAX 😁

I tried that it's like setting it back to default. It doesn't seem to recognize the value. But not all games are meant to have reverb especially Windows Hardware 3D Audio (non EAX versions) games and this introduces reverb that ALchemy didn't even. So like I don't want to get rid of reverb in all games just some. I would use ALchemy, but it can be pretty buggy and have sound artifacting where DSOAL+OpenAL-Soft doesn't.

**Comment by Kappa971** [comment]
> I tried that it's like setting it back to default. It doesn't seem to recognize the value. But not all games are meant to have reverb especially Windows Hardware 3D Audio (non EAX versions) games and this introduces reverb that ALchemy didn't even. So like I don't want to get rid of reverb in all games just some. I would use ALchemy, but it can be pretty buggy and have sound artifacting where DSOAL+OpenAL-Soft doesn't.

alsoft.ini must be located together with dsound.dll (DSOAL) or in C:\Users\%username%\AppData\Roaming

What do you mean by "Windows Hardware 3D Audio games"? If there are games that use DirectSound3D (3D audio) but without EAX (reverb and other effects), they probably have an option in the menu to disable EAX and only enable 3D audio. If the game doesn't allow you to do this, then you need to use 3D audio+EAX.

**Comment by Jenavieve-Rose** [comment]
> > I tried that it's like setting it back to default. It doesn't seem to recognize the value. But not all games are meant to have reverb especially Windows Hardware 3D Audio (non EAX versions) games and this introduces reverb that ALchemy didn't even. So like I don't want to get rid of reverb in all games just some. I would use ALchemy, but it can be pretty buggy and have sound artifacting where DSOAL+OpenAL-Soft doesn't.
> 
> alsoft.ini must be located together with dsound.dll (DSOAL) or in C:\Users\%username%\AppData\Roaming
> 
> What do you mean by "Windows Hardware 3D Audio games"? If there are games that use DirectSound3D (3D audio) but without EAX (reverb and other effects), they probably have an option in the menu to disable EAX and only enable 3D audio. If the game doesn't allow you to do this, then you need to use 3D audio+EAX.

I understand where the ini goes. Some games in the late 90's only use Microsoft DirectSound3D. Take Indiana Jones and the Infernal Machine it only supports DirectSound3D which gives you positional audio, but it never supported reverb. On the other hand, you have a game like The Phantom Menace which has an option for either DirectSound3d or DirectSound3D with Creative EAX. That game is fine it gives you both options and reverb effects work fine in it mostly. But Infernal Machine never had reverb and only has the option for DirectSound3D, and it isn't the only game like this, but suddenly with the newer version of DSOAL and OpenAL-Soft it does.

**Comment by Jenavieve-Rose** [comment]
Just compiled and tried the version of OpenAL-Soft literally made available today and it fixed the issue entirely. Looks like the issue was with OpenAL-Soft. Thanks for your time.

**Comment by hanfling** [comment]
Turns out it was actually outputting sound for me, but the distance attenuation appears to be broken (way to strong), so it was just not outputting any audible sound unless being very close to the source.

Tried latest openal-soft from github, here is the log:
[dsoal.log](https://github.com/kcat/dsoal/files/8240759/dsoal.log)

I can open another ticket if I find time to record a video showing it off better, etc.

**Comment by mirh** [comment]
@hanfling is that still a thing even in the latest versions?
