### ISSUE TITLE
EAX reverb is incorrectly assigned in some sounds

### ISSUE THREAD

**Issue by Kappa971** [kcat/dsoal#46]
EAX reverb is incorrectly assigned in some sounds.
These are some games I've tried:
1. In FEAR the reverb is audible in the menu.
2. In GTA 3 and GTA Vice City, reverb is also audible in radio stations.
3. In Splinter Cell and Splinter Cell Chaos Theory, reverb is also audible in radio conversations.

I guess other games might suffer from this problem as well.

**Comment by Jenavieve-Rose** [comment]
It seems to be introducing reverb in all games no matter what. In games that never used reverb not even when using ALchemy.

**Comment by Kappa971** [comment]
It appears that DSOAL or OpenAL Soft isn't turning off reverb in some sounds that shouldn't have it.

**Comment by kcat** [comment]
Try with the latest OpenAL Soft. It seems EAX wasn't properly disabling source sends when setting null effect slots.

**Comment by Jenavieve-Rose** [comment]
> Try with the latest OpenAL Soft. It seems EAX wasn't properly disabling source sends when setting null effect slots.

This fixed my issue #45  so it's possible these issues where related. Thanks

**Comment by Kappa971** [comment]
This seems to have solved the issue, thanks @kcat! 
I can close this.
