### ISSUE TITLE
Building latest master with CMake generates no dsound.dll

### ISSUE THREAD

**Issue by fearedbliss** [kcat/dsoal#48]
Hello,

I've attempted to build the latest master (fe2978f17) with CMake 3.22.3 and while the build succeeds, no dsound.dll is provided in the build directory or any other directories in the project. This seems to be a behavior change with CMake versions starting from 3.17 from the GH post here: https://github.com/gabime/spdlog/issues/1523.

```
CMake Warning (dev) at C:/Users/Jonathan/Desktop/cmake-3.22.3-windows-x86_64/share/cmake-3.22/Modules/GNUInstallDirs.cmake:239 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
The C compiler identification is MSVC 19.29.30133.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of long
Check size of long - done
Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Success
Performing Test HAVE_INLINE
Performing Test HAVE_INLINE - Success
Configuring done
Generating done
```

![image](https://user-images.githubusercontent.com/628436/159553134-21cbea6d-bd39-4c98-be5e-cf1e35dd7b6d.png)

Ultimately it would be better to have binary builds available as reported in #13 . This will allow downstream consumers to be able to easily test and provide these binaries to their users if needed. Ideally the linked OpenAL dll would also be included in the project as well (While giving credit to upstream) in order to allow the dll to be more easily used. At the moment there are too many steps for regular users to use this effectively, requiring someone with more knowledge to package it all up for them. I'm personally fine doing this for my users even if it creates a bit more maintenance burden for me, but I wanted to express that point.

EDIT: I've also tried getting an older version of CMake (The current documentation says CMake 2.6 or later), I was able to find an old CMake 2.6.4 (x86) build. Attempting to build with that one said the minimum CMake version for the project is 3.0.2. After that I found a CMake 3.0.2 build (x86) but had issues building it given the difference in toolchain versions and maybe some possible misconfiguration -.-.
 
Jonathan

**Comment by fearedbliss** [comment]
I was able to find the build artifacts hidden in the Actions section: https://github.com/kcat/dsoal/actions/runs/1937854569

I'll leave the ticket open since it seems we should be able to build these ourselves. But if anything, the documentation could be updated to reflect the build artifacts can be retrieved via the Actions tab rather than the "Releases" section.

**Comment by kcat** [comment]
I fixed the `CMAKE_INSTALL_LIBDIR` warning with commit 75f88e1bd9231d128ff38d99339680a86c45ccfb, though I doubt that's causing `dsound.dll` to not be built. Were there any issues during compilation? The compiler didn't error on one of the sources, and said where it wrote `dsound.dll`? Can you provide the compiler output?

**Comment by fearedbliss** [comment]
Hey @kcat ,

Thanks for responding. The output I posted yesterday was the build output coming from the `cmake-gui` command. I tried again with the `cmake` (cli) command and this is the stdout:

```
PS C:\Users\Jonathan\Desktop\AL\cmake-3.22.3-windows-x86_64\bin> .\cmake.exe ..\..\dsoal-master\ -B ..\..\dsoal-master\build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Success
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Jonathan/Desktop/AL/dsoal-master/build
PS C:\Users\Jonathan\Desktop\AL\cmake-3.22.3-windows-x86_64\bin>
```

The build artifacts in the `build` directory are basically the same as the screenshot I posted yesterday. No `dsound.dll`.

**Comment by kcat** [comment]
That's just the configuration step. You still need to build it by running
```
cmake --build ../../dsoal-master/build --config Release
```

**Comment by fearedbliss** [comment]
There we go ;D. As you can see I'm definitely not used to using cmake haha, but now that you mention it, it make sense.. similar to : `./configure && make`. It would be useful to have these two commands in the building from source section. I know the exact command may be machine dependent, but just a hint that there is a configure and a build step w/ the release profile would be helpful. Thanks for the help :).

```
PS C:\Users\Jonathan\Desktop\AL\cmake-3.22.3-windows-x86_64\bin> .\cmake.exe --build ..\..\dsoal-master\build --config Release
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/dsoal-master/CMakeLists.txt
  buffer.c
  capture.c
  dsound8.c
  dsound_main.c
  duplex.c
  eax.c
  primary.c
  propset.c
  voiceman.c
  debug.c
C:\Users\Jonathan\Desktop\AL\dsoal-master\debug.c(69,22): warning C4244: '=': conversion from '__int64' to 'int', possi
ble loss of data [C:\Users\Jonathan\Desktop\AL\dsoal-master\build\dsound.vcxproj]
  Generating Code...
     Creating library C:/Users/Jonathan/Desktop/AL/dsoal-master/build/Release/dsound.lib and object C:/Users/Jonathan/D
  esktop/AL/dsoal-master/build/Release/dsound.exp
  dsound.vcxproj -> C:\Users\Jonathan\Desktop\AL\dsoal-master\build\Release\dsound.dll
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/dsoal-master/CMakeLists.txt
PS C:\Users\Jonathan\Desktop\AL\cmake-3.22.3-windows-x86_64\bin>
```
