### ISSUE TITLE
Diablo 2: No "Environmental Effects" support

### ISSUE THREAD

**Issue by fearedbliss** [kcat/dsoal#49]
Hello,

I was able to find the latest 'dsound.dll' by going to the Actions tab and getting the dll for the latest commit. After this, I combined the dll with the latest OpenAL Soft 1.21.1 dll and launch Diablo II with it. The game loaded up fine and basic sound worked. The "3D Sound" and "3D Bias" options were allowed to be enabled and modified, however the "Environmental Effects" option is still disabled. This may indicate that the dsoal dsound.dll is not properly "faking" it's EAX support to the game. Once we can get EAX enabled, I'll be able to test to see if the actual sounds sound different than the 2D sounds and if EAX are working correctly. I've previously tested two different implementations from some other people / projects so I have a relatively better idea of how an improved 3D/EAX sound is suppose to sound like. 

For your reference, this is a video comparing the previous two sound implementations (to be clear though, the IndirectSound documentation states that they don't actually support EAX yet, they only support faking support, so the option in the game is allowed to be changed, but it makes no sound changes. The BURAOT implementation does provide a good and significant sound difference for 3D and EAX):

https://odysee.com/@TheCactusSanctuary:f/-Diablo-II--3D-Sound-Comparison---BURAOT-vs-IndirectSound-%28Included-in-Cactus%29:b

![Screenshot001](https://user-images.githubusercontent.com/628436/159560289-d622bb53-3b4b-4e4b-8b9e-1829e31cf5a5.jpg)

Jonathan

**Comment by kcat** [comment]
Are you able to get a DSOAL log with the game? If you set the `DSOAL_LOGLEVEL` environment variable to `3`, and the `DSOAL_LOGFILE` environment variable to a path+filename the app can write to, it'll write a log to the given filename of what the game is trying to do, which can shed light on why it may not think Environmental Effects aren't available.

**Comment by fearedbliss** [comment]
Hey @kcat,

I was able to successfully get the debug file. I've attached it below:

[d2-1.txt](https://github.com/kcat/dsoal/files/8333289/d2-1.txt)

I started the game with the "3D Sound" option enabled. Then I played around with 3D Bias (sliding to the left and to the right) and then turned the "3D Sound" option on and off. I did this primarily to generate more debug output in case that helps.

I saw the following lines in the debug file which I believe are related to Environmental Effects support for 1.0 and 2.0:

Line 83
```
0648:trace:dsound:DSBufferProp_QuerySupport (0BD91274)->(DSPROPSETID_EAX20_ListenerProperties, 0x1, 0019F09C)
```

Line 108
```
0648:trace:dsound:DSBufferProp_QuerySupport (0BD91274)->(DSPROPSETID_EAX10_ListenerProperties, 0x0, 0019F09C)
```

Jonathan

**Comment by kcat** [comment]
It looks like a version mismatch.
```
0648:trace:dsound:DSShare_Create Found AL_EXT_FLOAT32
0648:trace:dsound:DSShare_Create Found AL_EXT_MCFORMATS
0648:trace:dsound:DSShare_Create Found AL_SOFT_deferred_updates
0648:trace:dsound:DSShare_Create Found AL_SOFT_source_spatialize
0648:trace:dsound:DSShare_Create Found AL_SOFTX_map_buffer
```
It's not finding `EAX5.0` or `ALC_EXT_EFX`, meaning it's a more recent DSOAL (which is looking for EAX instead of EFX) with an older OpenAL Soft (which doesn't have EAX). Either that, or EAX is disabled.

Make sure you're using a recent build from Git of both DSOAL and OpenAL Soft, and the OpenAL Soft DLL is renamed to `dsoal-aldrv.dll`.

**Comment by fearedbliss** [comment]
Hey @kcat , Will try it again now that we got the `dsound.dll` to build. As I stated in my original post, I used the latest `dsound.dll` that was provided in this project's Action tab, and used the latest binary build of OpenAL Soft 1.21.1 that was available on the website. So those should technically be the latest in terms of code bases and compatibility. The dll was named correctly and the screenshot above shows that the game did load and sound works but just that the EAX sections weren't working.

**Comment by kcat** [comment]
> Hey @kcat , Will try it again now that we got the `dsound.dll` to build. As I stated in my original post, I used the latest `dsound.dll` that was provided in this project's Action tab, and used the latest binary build of OpenAL Soft 1.21.1 that was available on the website. So those should technically be the latest in terms of code bases and compatibility.

1.21.1 is the latest release, but you need the latest Git version for the EAX extensions, which is needed by the latest Git version of DSOAL needs for effects support. You can get prebuilt OpenAL Soft DLLs from AppVeyor:

https://ci.appveyor.com/project/ChrisRobinson/openal-soft

Click the environment for the build you need (e.g. `ARCH=Win32 CFG=Release` for the 32-bit release build, or `ARCH=x64 CFG=Release` for the 64-bit release build), then click the Artifacts tab for a zip file with the dll.

**Comment by fearedbliss** [comment]
Thanks @kcat . I've downloaded and compiled the latest commit for open al soft as well. I tested them both out but now the dll doesn't even load. I remember before if I tested just the `dsound.dll` (without the openal dll - on purpose!) I was able to get a crash behavior which was good. Once the openal dll was provided, it loaded but EAX wasn't enabled.

For the new `dsound.dll` that I built locally, dropping that file alone doesn't seem to replicate a crash behavior. The game also loaded without any of the 3D options even being available now. Providing the newly built `dsoal-aldrv.dll` (Build at `OpenAL32.dll` on the same toolchain as our `dsound.dll`), also didn't fix this. I tried to log output again using our previous method and I wasn't able to get any log to be displayed. So either the dll `dsound.dll` that we successfully built is now no longer being loaded (mostly likely the reason, although not sure why that would be), or the dll is failing early enough in the process where a crash message isn't being displayed (More unlikely).

**Comment by fearedbliss** [comment]
I'm providing the dlls here (I'm not sure if you'll need to inspect them for anything, but they were built with the same toolchain and the output for these dlls was provided in the previous posts):

[sound1.zip](https://github.com/kcat/dsoal/files/8337282/sound1.zip)

**Comment by fearedbliss** [comment]
Using the artifacts from the latest OpenAL in conjunction with the latest artifacts from the DSOAL Action's tab allowed the 3D Sound option to be displayed and the EAX option as well. I also tested to see if I can hear the difference with the EAX enabled and so far it seems like it's working great :). So this good. Maybe CMake is building the project correctly but for whatever reason the DLLs generated by my toolchain are not being "liked" by the game.

**Comment by fearedbliss** [comment]
Good news :). Seems my observation was correct. The previous binaries were being built for 64 bit. I've specified the 32 bit arch for both projects and rebuilt and now the dll crashes correctly when not provided the `dsoal-aldrv.dll`. The dll loads successfully and environmental effects work as well when I do provide the dll.

Thanks for the help :). I'll be switching my Cactus (Modern Diablo II Version Switcher) to include your implementation rather than my previous one.

I'll put the build output below for the 32 bit build. Also for people that just want the two commands for building with the 32 bit arch (Assuming you are in the source directory):

```
cmake -A Win32 -B build
cmake --build build --config Release
```

Once that's done you can rename the OpenAL Soft's `OpenAL32.dll` to `dsoal-aldrv.dll` as described in the documentation.

```
PS C:\Users\Jonathan\Desktop\AL\dsoal> cmake -A Win32 -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Failed
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC - Success
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Jonathan/Desktop/AL/dsoal/build

PS C:\Users\Jonathan\Desktop\AL\dsoal> cmake --build build --config Release
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/dsoal/CMakeLists.txt
  buffer.c
  capture.c
  dsound8.c
  dsound_main.c
  duplex.c
  eax.c
  primary.c
  propset.c
  voiceman.c
  debug.c
  Generating Code...
     Creating library C:/Users/Jonathan/Desktop/AL/dsoal/build/Release/dsound.lib and object C:/Users/Jonathan/Desktop/
  AL/dsoal/build/Release/dsound.exp
  dsound.vcxproj -> C:\Users\Jonathan\Desktop\AL\dsoal\build\Release\dsound.dll
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/dsoal/CMakeLists.txt
  
  
 PS C:\Users\Jonathan\Desktop\AL\openal-soft> cmake -A Win32 -B build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Performing Test HAVE___RESTRICT
-- Performing Test HAVE___RESTRICT - Success
-- Performing Test HAVE_LIBATOMIC
-- Performing Test HAVE_LIBATOMIC - Failed
-- Performing Test HAVE_PERMISSIVE_SWITCH
-- Performing Test HAVE_PERMISSIVE_SWITCH - Success
-- Performing Test HAVE_MSSE2_SWITCH
-- Performing Test HAVE_MSSE2_SWITCH - Failed
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for pmmintrin.h
-- Looking for pmmintrin.h - found
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - not found
-- Performing Test HAVE_ARCH_SSE2
-- Performing Test HAVE_ARCH_SSE2 - Success
-- Performing Test HAVE_SSE_INTRINSICS
-- Performing Test HAVE_SSE_INTRINSICS - Success
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for cpuid.h
-- Looking for cpuid.h - not found
-- Looking for intrin.h
-- Looking for intrin.h - found
-- Looking for guiddef.h
-- Looking for guiddef.h - found
-- Looking for pow in m
-- Looking for pow in m - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - not found
-- Performing Test HAVE_CPUID_INTRINSIC
-- Performing Test HAVE_CPUID_INTRINSIC - Success
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - found
-- Looking for proc_pidpath
-- Looking for proc_pidpath - not found
-- Looking for getopt
-- Looking for getopt - not found
-- Could NOT find DBus1 (missing: DBus1_INCLUDE_DIRS DBus1_LIBRARIES)
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Looking for dsound.h
-- Looking for dsound.h - found
-- Looking for mmdeviceapi.h
-- Looking for mmdeviceapi.h - found
-- Could NOT find PortAudio (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)
-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Could NOT find OpenSL (missing: OPENSL_LIBRARY OPENSL_INCLUDE_DIR OPENSL_ANDROID_INCLUDE_DIR)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.35.1.windows.2")
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find MySOFA (missing: MYSOFA_LIBRARY MYSOFA_INCLUDE_DIR ZLIB_FOUND)
-- Could NOT find Qt5Widgets
-- Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
--
-- Building OpenAL with support for the following backends:
--     WinMM, DirectSound, WASAPI, WaveFile, Null
--
-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE3, SSE4.1
--
-- Building with SSE2 codegen
--
-- Building with legacy EAX extension support
--
-- Embedding HRTF datasets
--
-- Installing library and headers
-- Installing sample configuration
-- Installing HRTF data files
-- Installing AmbDec presets
--
-- Building utility programs
--
-- Building example programs
--
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Jonathan/Desktop/AL/openal-soft/build
PS C:\Users\Jonathan\Desktop\AL\openal-soft> cmake --build build --config Release
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  alcomplex.cpp
  alfstream.cpp
  almalloc.cpp
  alstring.cpp
  dynload.cpp
  polyphase_resampler.cpp
  ringbuffer.cpp
  strutils.cpp
  threads.cpp
  Generating Code...
  common.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\common.lib
  Generating hrtf_default.h
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  auxeffectslot.cpp
  buffer.cpp
  effect.cpp
  effects.cpp
  error.cpp
  event.cpp
  extension.cpp
  filter.cpp
  listener.cpp
  source.cpp
  state.cpp
  eax_api.cpp
  eax_eax_call.cpp
  eax_effect.cpp
  eax_exception.cpp
  eax_fx_slot_index.cpp
  eax_fx_slots.cpp
  eax_globals.cpp
  eax_utils.cpp
  eax_x_ram.cpp
  Generating Code...
  Compiling...
  alc.cpp
  alu.cpp
  alconfig.cpp
  panning.cpp
  base.cpp
  loopback.cpp
  winmm.cpp
  dsound.cpp
  wasapi.cpp
  wave.cpp
  ambdec.cpp
  ambidefs.cpp
  bformatdec.cpp
  bs2b.cpp
  bsinc_tables.cpp
  buffer_storage.cpp
  converter.cpp
  cpu_caps.cpp
  devformat.cpp
  effectslot.cpp
  Generating Code...
  Compiling...
  except.cpp
  biquad.cpp
  nfc.cpp
  splitter.cpp
  fmt_traits.cpp
  fpu_ctrl.cpp
  helpers.cpp
  hrtf.cpp
  logging.cpp
  mastering.cpp
  mixer.cpp
  uhjfilter.cpp
  uiddefs.cpp
  voice.cpp
  mixer_c.cpp
  mixer_sse.cpp
  mixer_sse2.cpp
  mixer_sse3.cpp
  mixer_sse41.cpp
  Generating Code...
  autowah.cpp
  chorus.cpp
  compressor.cpp
  convolution.cpp
  dedicated.cpp
  distortion.cpp
  echo.cpp
  equalizer.cpp
  fshifter.cpp
  modulator.cpp
  null.cpp
  pshifter.cpp
  reverb.cpp
  vmorpher.cpp
  context.cpp
  device.cpp
  autowah.cpp
  chorus.cpp
  compressor.cpp
  convolution.cpp
  dedicated.cpp
  distortion.cpp
  echo.cpp
  equalizer.cpp
  fshifter.cpp
  modulator.cpp
  null.cpp
  pshifter.cpp
  reverb.cpp
  vmorpher.cpp
  null.cpp
  context.cpp
  device.cpp
     Creating library C:/Users/Jonathan/Desktop/AL/openal-soft/build/Release/OpenAL32.lib and object C:/Users/Jonathan/
  Desktop/AL/openal-soft/build/Release/OpenAL32.exp
  OpenAL.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\OpenAL32.dll
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  alhelpers.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion produc
ing 'defined' has undefined behavior [C:\Users\Jonathan\Desktop\AL\openal-soft\build\ex-common.vcxproj]
  ex-common.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\ex-common.lib
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  alrecord.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion produc
ing 'defined' has undefined behavior [C:\Users\Jonathan\Desktop\AL\openal-soft\build\alrecord.vcxproj]
  alrecord.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\alrecord.exe
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  altonegen.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion produc
ing 'defined' has undefined behavior [C:\Users\Jonathan\Desktop\AL\openal-soft\build\altonegen.vcxproj]
  altonegen.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\altonegen.exe
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
  openal-info.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion produc
ing 'defined' has undefined behavior [C:\Users\Jonathan\Desktop\AL\openal-soft\build\openal-info.vcxproj]
  openal-info.vcxproj -> C:\Users\Jonathan\Desktop\AL\openal-soft\build\Release\openal-info.exe
  Building Custom Rule C:/Users/Jonathan/Desktop/AL/openal-soft/CMakeLists.txt
PS C:\Users\Jonathan\Desktop\AL\openal-soft>
```
