### ISSUE TITLE
soft_oal.dll in SysWow64?

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/dsoal#55]
Sorry I could not find an answer to this and there is no place that I could find to ask general questions. If I am building OpenAL-Soft myself and putting the soft_oal.dll in the proper windows directories like SysWow64 do I still need to put a dsoal-aldrv.dll next to my dsound.dll in every game? Or can I just use the dsound.dll and it knows to call out to the soft_oal.dll in the windows directory?

**Comment by Jenavieve-Rose** [comment]
> You can put dsoal-aldrv.dll in SysWow64 so that you don't have to copy it for every game.

Thank's that is incredibly helpful to know. Especially since I have a lot of games and every time I compile a new version of OpenAL-Soft I spend like a half hour copying it to game directories lol.

**Comment by drivetheory** [comment]
fwiw the WOW in SysWOW64 stands for Windows (32-bit) On Windows 64-bit.
in x64 windows, system32 is used by 64-bit environments and SysWOW64 is used by 32-bit environments.
