### ISSUE TITLE
Batman: Vengeance - Errors and crash

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/dsoal#59]
Just like #41, [QSound demo](https://airtable.com/shrtTsUtiAJQ7wFGI/tblNOTdmp5nHXfFGU/viwjDPuKOjBnIQunv/recEQtwAwrC2UxVls), [Duke Nukem: Manhattan Project](https://airtable.com/shrtTsUtiAJQ7wFGI/tblNOTdmp5nHXfFGU/viwjDPuKOjBnIQunv/reci4yDhRs88GuKu0) and a few others, [this game](https://airtable.com/shrtTsUtiAJQ7wFGI/tblNOTdmp5nHXfFGU/viwjDPuKOjBnIQunv/recmfdU6fOjjT1575) used to require [DSOAL v1.1](https://www.nexusmods.com/newvegas/mods/65094?tab=files)/[DSOAL-XP](https://github.com/pachuco/dsoal-XP/tree/master/release) to prevent crash on startup, but that got fixed with 910cf95edc7c36113e949fa073cae637d3b44557 🎉
However, I still get some errors while playing/loading screens like this:
![image](https://user-images.githubusercontent.com/71472458/177674939-95f3240d-9c8d-43c9-98f7-bbcb629113ca.png)
Some can be skipped by mashing enter/OK but sometimes it eventually just crashes.

Recording: https://i.imgur.com/eVkXJXF.mp4
Game demo: https://archive.org/download/batman_pc_demo1_zip/batman_pc_demo1.zip
[dsoal_error.txt](https://github.com/kcat/dsoal/files/9059775/dsoal_error.txt)
[alsoft_error.txt](https://github.com/kcat/dsoal/files/9059776/alsoft_error.txt)

**Comment by kcat** [comment]
Looks like an issue of running out of sources:
```
3724:trace:dsound:DS8_DuplicateSoundBuffer (0BAE0B60)->(0BB46118, 0019F9D0)
3724:trace:dsound:DSBuffer_GetCaps (0BB46118)->(0019F99C)
3724:trace:dsound:DSBuffer_Initialize (0BBA26A8)->(00000000, 00000000)
3724:err:dsound:DSBuffer_SetLoc Out of software sources
```
DSOAL was only able to get 256 sources (128 hardware, 128 software), it seems because to configured OpenAL Soft to 256 sources so DSOAL isn't able to request more.

**Comment by ThreeDeeJay** [comment]
I see. I set `sources=512` and was able to play all the demo levels without a single error/crash👌
Too bad the game doesn't seem to use DS3D so it's just virtualized stereo 
But oh well, guess I'll go ahead and close this issue then
