### ISSUE TITLE
EAX Advanced HD: The Gold Mine Experience - Fails to detect EAX

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/dsoal#60]
[Info](https://airtable.com/shrpPCOJwJiA8T8Hr/tbl3TyLn23qfBWZTz/viwEFl4VhIITjGRw1/recWutmzqc0ssTSrr)
[Demo](https://youtu.be/_-dW5Zyv8Kc)
[Download](https://www.dropbox.com/s/8bpv6ywdc0yh9bq/EAX%20Goldmine.7z?dl=1)
[Source](https://www.vogonsdrivers.com/getfile.php?fileid=397)
Error:
![image](https://user-images.githubusercontent.com/71472458/178885414-f4093412-404e-4c57-b5da-c83f64b621f3.png)
[alsoft.ini](https://pastebin.com/raw/chF4TXEy)
[alsoft_error.txt](https://github.com/kcat/dsoal/files/9108173/alsoft_error.txt)
*dsoal_error.txt doesn't get created

This neat tool showcases EAX Advanced HD features (reflections, environment morphing, exclusion, occlusion, obstruction, etc) so I figured I'd give it a try with DSOAL, but unfortunately I'm getting the error above in both latest build and even [DSOAL-XP](https://github.com/pachuco/dsoal-XP/tree/master/release), probably because this was meant for old sound cards like Audigy and not even ALchemy is detected, but [it works on Windows XP with my Sound Blaster X-Fi Surround 5.1 (SB1090)](https://youtu.be/QIXbIt0_6mM), which supports [up to EAX 4](https://i.imgur.com/1x8atsB.png) and I think is from 2010 so I doubt this demo is locked to specific hardware IDs like the [main setup file](https://i.imgur.com/XsC4Tg8.jpeg).
I also tried running as administrator and every compatibility mode available on Windows 10 without luck and on my Windows 11 VM I got a [different error](https://i.imgur.com/HFbOxJM.jpeg), and I'm not sure if it expects specific values in alsoft.ini to imitate contemporary hardware.

EDIT: Tested [DSOAL-XP](https://github.com/pachuco/dsoal-XP/tree/master/release) with the same [alsoft.ini](https://pastebin.com/raw/chF4TXEy) on Windows XP and it worked even though it didn't on Win10/11, so maybe some change in newer Windows versions might have broken compatibility with this program.
[dsoal_error.txt](https://github.com/kcat/dsoal/files/9108469/dsoal_error.txt)
[alsoft_error.txt](https://github.com/kcat/dsoal/files/9108470/alsoft_error.txt)

**Comment by kcat** [comment]
That a DSOAL log isn't created, and ALchemy also doesn't work, that makes it seem like it's not even trying DSound on Vista and newer (which would make some sense, since Creative would know hardware DSound support was removed after XP), which would also explain why it works on XP.

That an OpenAL Soft log is created would then suggest it's trying to use OpenAL instead, and the reason that's not working is it's picking up OpenAL Soft 1.21.1, which doesn't support the EAX extensions. Though it's a bit odd it's not picking up the X-Fi's native OpenAL driver, unless that's not available (on 32-bit) or you replaced the router so it's not used.

**Comment by ThreeDeeJay** [comment]
Right on the money, as usual 👌
It was indeed using OpenAL so the DSOAL dlls were being ignored and instead used the ones in the system folder, where I had some outdated OpenAL Soft DLLs since I usually just rename it to OpenAL32.dll and drop it directly into the game folder to skip the router.
The weird thing is that some of the app's files date back to 2001 (the app was bundled with Audigy drivers) so I wonder how it knows when to switch APIs which I didn't even know was a thing long before Vista. 🤔
Either way, I recorded some footage to check if EAX is working properly: https://youtu.be/KmmClkWaUu8
First demo I linked which seems to be using a real Audigy https://youtu.be/_-dW5Zyv8Kc

**Comment by mirh** [comment]
OpenAL has been a thing long before vista. 
https://www.linuxjournal.com/article/4400
https://web.archive.org/web/20010404232451/http://www.zdnet.com/gshw/stories/news/0,12836,2700843,00.html
In fact, I suspect OpenAL may have been shipping even before the Audigy. 
https://sg.creative.com/corporate/pressroom?id=6422
This demo if any was the first eyecandy with EAX3. 
https://www.tomshardware.com/reviews/big-sound,370-13.html
