### ISSUE TITLE
F.E.A.R. won't load dsound.dll, all sound options greyed out (Wine)

### ISSUE THREAD

**Issue by mrmatteastwood** [kcat/dsoal#67]
Hey DSOAL community,

When launching, F.E.A.R. seems to completely ignore/bypass dsound.dll and dsoal-aldrv.dll in its root folder. All surround sound options are greyed out in the sound menu (like on this screenshot: https://www.pcgamingwiki.com/wiki/F.E.A.R.#/media/File:FEAR_Audio.png).

I'm using Wine 7.14 (staging) on Linux Mint 21. I have one other game (Duke Nukem Manhattan Project) that works with DSOAL, and when I run it, I get a DSOAL logfile. However, when I run F.E.A.R., there's no log file, leading to my suspicion that it doesn't recognize or acknowledge DSOAL.

FWIW, I tried IndirectSound, same result. I set FEAR.exe to Windows XP mode in winecfg, the dsound library to "native, builtin" and openal32 to builtin.

Here's the stderr output:

```
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.14 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
007c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
007c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
007c:fixme:xinput:pdo_pnp IRP_MN_QUERY_ID type 5, not implemented!
0128:fixme:system:NtUserSystemParametersInfo Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0128:fixme:system:NtUserSystemParametersInfo Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0128:fixme:system:NtUserSystemParametersInfo Unimplemented action: 51 (SPI_SETFILTERKEYS)
0090:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
0128:fixme:imm:ImeSetActiveContext (00010064, 1): stub
0090:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
0128:fixme:imm:ImmReleaseContext (00020068, 00010064): stub
0128:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0128:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x30
0128:fixme:wbemprox:enum_class_object_Next timeout not supported
0128:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
0128:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
0128:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
0128:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
0128:fixme:d3d:wined3d_device_set_software_vertex_processing device 008DDF60, software 0 stub!
0148:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0148:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #3:
0148:fixme:d3d_shader:print_glsl_info_log     Vertex info
0148:fixme:d3d_shader:print_glsl_info_log     -----------
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[0].zw" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[1]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[2]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[3]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[4]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[5]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[6]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[7]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[9]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[11]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #7:
0148:fixme:d3d_shader:print_glsl_info_log     Vertex info
0148:fixme:d3d_shader:print_glsl_info_log     -----------
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[0].zw" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[1]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[2]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[3]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[4]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[5]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[6]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[7]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[9]" might be used before being initialized
0148:fixme:d3d_shader:print_glsl_info_log     0(29) : warning C7050: "vs_out[11]" might be used before being initialized
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_sub_resource_map Failed to prepare location.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_sub_resource_map Failed to prepare location.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37B674E0 sub-resource 0 with resource access WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37B66DE8 sub-resource 0 with resource access WINED3D_RESOURCE_ACCESS_GPU | WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_sub_resource_map Failed to prepare location.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_sub_resource_map Failed to prepare location.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37BBD980 sub-resource 0 with resource access WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37BBD288 sub-resource 0 with resource access WINED3D_RESOURCE_ACCESS_GPU | WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37BBD288 sub-resource 1 with resource access WINED3D_RESOURCE_ACCESS_GPU | WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0148:err:d3d:wined3d_resource_allocate_sysmem Failed to allocate system memory.
0148:err:d3d:texture_resource_unload Discarding WINED3D_RTYPE_TEXTURE_2D 37BBD288 sub-resource 2 with resource access WINED3D_RESOURCE_ACCESS_GPU | WINED3D_RESOURCE_ACCESS_CPU | WINED3D_RESOURCE_ACCESS_MAP_R | WINED3D_RESOURCE_ACCESS_MAP_W.
0128:err:msacm:MSACM_GetRegistryKey No alias needed for registry entry
```

**Comment by kcat** [comment]
For some reason, FEAR will only load dsound.dll from `c:\windows\syswow64` (what would be `c:\windows\system32` on 32-bit Windows). I don't know if there's a way to make it recognize the DLL placed in the game directory, but the only way I know that works is to replace the system DLL (if you do that, be sure to back up the original file so you can restore it afterward; I don't recommend leaving dsoal as the system dsound when not needed).

**Comment by mrmatteastwood** [comment]
It works! Thanks :-)

**Comment by mirh** [comment]
The reason probably being COM 
#11

**Comment by mrmatteastwood** [comment]
For anybody interested, I re-tested this today using my very latest setup with Linux Mint 21.1 and a completely fresh install of F.E.A.R.. First-time install through Lutris since setting up Linux Mint 21.1 from scratch on my desktop PC back in December. FWIW, I'm gonna leave a full, detailed report here.

**// SUMMARY - how to get it to work**

F.E.A.R. surround sound works fully when putting DSOAL's two dll files into the same directory as FEAR.exe, dsound.dll into drive_c/windows/syswow64, and then setting both Win XP compatibility mode and dsound = native for FEAR.exe using winecfg.


**/// Installation stumbling using Lutris**

I have F.E.A.R. Platinum Collection on GOG and installed it through Lutris 0.5.12 from Mint repos (i.e., not Flatpak). Lutris detected my system-wide Wine installation, version 8.1 (staging).

I installed F.E.A.R. using the "wine - GOG install" option, i.e. not the second one, "wine - GOG (auto-generated)". I chose only to install the base game, none of the extra content (Wallpaper, Commentary etc.).

During installation, I got an error dialog, "Command exited with code 13568". Screenshot of install screen: https://paste.pics/LN6BJ.

I'm already used to that, Lutris has worked that way on my PC since I first tried it. I cancelled, removing game files, and restarted the installation from scratch and the 2nd one went through.


**/// Current Results**

...running without any changes to config or directory:
...running with DSOAL's dsound.dll and dsoal-aldrv.dll in same directory as FEAR.EXE:
...running with DSOAL's dsound.dll in drive_c/windows/syswow64 directory (original dsound.dll renamed) and dsoal-aldrv.dll in same directory as FEAR.EXE:

=> Stereo sound, last 3 sound options greyed out (EAX etc.).
=> Sound crackles badly in front left speaker, sudden overall volume spikes when navigating the menu

...running with the following set-up:

**- FEAR.exe set to Win XP compatibility in winecfg
- dsound set to "native" in winecfg for FEAR.exe
- DSOAL's dsound.dll in drive_c/windows/syswow64
- DSOAL's dsound.dll and dsoal-aldrv.dll in same directory as FEAR.EXE

=> Everything works!**

...running without any changes to config or directory, BUT with the first fix (registry edit) proposed here - https://bugs.winehq.org/show_bug.cgi?id=53553#c4:
...running without any changes to config or directory, BUT with the second fix (register dsound) proposed here - https://bugs.winehq.org/show_bug.cgi?id=53553#c4:

=> Stereo sound, last 3 sound options greyed out (EAX etc.).
=> Sound crackles badly in front left speaker, sudden overall volume spikes when navigating the menu


**/// Installed versions**

Lutris: 0.5.12 from Mint repos (i.e., not Flatpak)
Wine: 8.1 staging from PPA


**/// PC specs (report by Lutris):
/// (Linux Mint's report: https://termbin.com/ejwr)**

[System]
OS:              Linux Mint 21.1 Vera
Arch:            x86_64
Kernel:          6.0.0-1011-oem
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             31.3 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.78.01
OpenGL Core:     4.6.0 NVIDIA 525.78.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.78.01
Vulkan:          Supported

**Comment by jvalecillos** [comment]
Hey @StealthRook, sorry for the late reply.

That `SndDrv.dll` error tells me that you are using the second method and probably missing the required registry keys. As I mentioned in my original comment, this happens when WINE forces the native DLL (`dsound.dll=n`) but cannot find the proper components.

Let me summarize here what you can do:

1. Make sure you have copied the `dsound.dll` and `dsoal-aldrv.dll` files (from this project) next to the game executable.
2. Download the [DirectSound Wrapper Registry Patcher v1.2](https://github.com/ThreeDeeJay/DSWRP/releases/tag/v1.2.0) (version 1.3 doesn't work on Wine now).
3. Extract both `DirectSound Wrapper Registry Patcher.cmd` and `SetACL.exe` somewhere (e.g. into your game directory). You need both files.
4. Run the Patcher: You must execute the `.cmd` file inside the WINE/Proton prefix.
  * Temporarily change your launcher (Steam, Lutris, etc.) to point to `DirectSound Wrapper Registry Patcher.cmd` instead of the game's executable.
  * Run the game entry and wait for the terminal window to close after the changes are applied.
5. Set the DLL override to use only the native version: `dsound.dll=n`. (It is `WINEDLLOVERRIDES="dsound.dll=n" %command%` if using Steam).
6. Change your launcher setting back to the original game executable.

I hope this helps.

Edit: I forgot the obvious step of the DLL override. I added the step by the end in case you want to run the game once before applying the registry changes.

**Comment by mirh** [comment]
Does 1.3 work if you remove [this](https://github.com/ThreeDeeJay/DSWRP/blob/v1.3.0/DirectSound%20Wrapper%20Registry%20Patcher.cmd#L27) line?

**Comment by jvalecillos** [comment]
@mirh Yes, that did the trick. Before with the `whoami /groups | find "S-1-16-12288" > nul` line I got the following error:
```
Can't recognize 'MODE con: cols=150 lines=50' as an internal or external command, or batch script.

Registering DirectSound references (dsound.dll)...
Failed to acquire elevation. Please, close this window and then right click this .cmd file > Run as administrator
Press any key to continue...
```
Obviously, there's no such thing as `Run as administrator` with Wine/Proton.

Once you remove the line, the registry keys are created as expected.

The mode error is present on the previous version and it doesn't affect anything, it is probably related with Wine not supporting changing the size of the window.

**Comment by jvalecillos** [comment]
Also, I'd like to reiterate that the script from [ThreeDeeJay/DSWRP](https://github.com/ThreeDeeJay/DSWRP) adds more registry keys than are actually needed for **F.E.A.R.**

I created my own registry file with only the minimum necessary keys, following the [documentation from IndirectSound](https://www.indirectsound.com/registryIssues.html). They are as follows:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}\InprocServer32]
@="dsound.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}\InprocServer32]
@="dsound.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}\InprocServer32]
@="dsound.dll"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}]

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}\InprocServer32]
@="dsound.dll"
```

You can save that as a `.reg` file and add it to the registry. With Lutris, it's super easy because it has a menu option for it.

**Comment by StealthRook** [comment]
Hi everyone! Thank you all for replies, I will try your recommendations in the next few days

**Comment by StealthRook** [comment]
> Also, I'd like to reiterate that the script from [ThreeDeeJay/DSWRP](https://github.com/ThreeDeeJay/DSWRP) adds more registry keys than are actually needed for **F.E.A.R.**
> 
> I created my own registry file with only the minimum necessary keys, following the [documentation from IndirectSound](https://www.indirectsound.com/registryIssues.html). They are as follows:
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}\InprocServer32]
> @="dsound.dll"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}\InprocServer32]
> @="dsound.dll"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{3901CC3F-84B5-4FA4-BA35-AA8172B8A09B}\InprocServer32]
> @="dsound.dll"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}]
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\CLSID\{47D4D946-62E8-11CF-93BC-444553540000}\InprocServer32]
> @="dsound.dll"
> 
> You can save that as a `.reg` file and add it to the registry. With Lutris, it's super easy because it has a menu option for it.

Hi, @jvalecillos! I've tried your script and it worked like a charm! I actually combined it with @ThreeDeeJay's patcher, but it's probably not necessary.

So, my steps were these:

1. I downloaded DSOAL V1.4 https://community.pcgamingwiki.com/files/file/1363-dsoal/, EAX Unified https://community.pcgamingwiki.com/files/file/367-eax-unified/ and OpenAL https://openal.org/downloads/

2. Then I unpacked DSOAL to game's directory

3. Then in desktop mode I used Protontricks and installed EAX Unified and OpenAL. And in "Install a Windows DLL or component" I installed dsound

4. After that I opened regedit and imported your script as .reg file. I also used @ThreeDeeJay's patcher, but as I said before it's probably not important

5. And in Steam I already had WINEDLLOVERRIDES="dsound=n,b" %command%

Thank you so much for your help!

**Comment by ThreeDeeJay** [comment]
@jvalecillos @mirh Does this one work?
https://raw.githubusercontent.com/ThreeDeeJay/DSWRP/refs/heads/WINE/DirectSound%20Wrapper%20Registry%20Patcher.cmd
I added a conditional following [this suggestion](https://github.com/ThreeDeeJay/DSWRP/issues/3#issuecomment-3940960801) that skips the `whoami ...` line when the WINE environment variable is defined (and same for `MODE ...` since I saw an error that also seems Wine-specific.)

**Comment by jvalecillos** [comment]
About the script:

> [@jvalecillos](https://github.com/jvalecillos) [@mirh](https://github.com/mirh) Does this one work? https://raw.githubusercontent.com/ThreeDeeJay/DSWRP/refs/heads/WINE/DirectSound%20Wrapper%20Registry%20Patcher.cmd I added a conditional following [this suggestion](https://github.com/ThreeDeeJay/DSWRP/issues/3#issuecomment-3940960801) that skips the `whoami ...` line when the WINE environment variable is defined (and same for `MODE ...` since I saw an error that also seems Wine-specific.)

@ThreeDeeJay Yes, that version of the script executed correctly.

While testing this, I also discovered an existent non-breaking bug. The unified `Backup.reg` file isn't being created correctly using Wine/Proton. If I have time, I'll send you a PR later.

<img width="1330" height="868" alt="cmd script output" src="https://github.com/user-attachments/assets/4072aced-8c4e-42cf-8646-d876c6a5cb87" />

About the steps:

> Hi, [@jvalecillos](https://github.com/jvalecillos)! I've tried your script and it worked like a charm! I actually combined it with [@ThreeDeeJay](https://github.com/ThreeDeeJay)'s patcher, but it's probably not necessary.
> 
> So, my steps were these:
> 
>     1. I downloaded DSOAL V1.4 https://community.pcgamingwiki.com/files/file/1363-dsoal/, EAX Unified https://community.pcgamingwiki.com/files/file/367-eax-unified/ and OpenAL https://openal.org/downloads/
> 
>     2. Then I unpacked DSOAL to game's directory
> 
>     3. Then in desktop mode I used Protontricks and installed EAX Unified and OpenAL. And in "Install a Windows DLL or component" I installed dsound
> 
>     4. After that I opened regedit and imported your script as .reg file. I also used [@ThreeDeeJay](https://github.com/ThreeDeeJay)'s patcher, but as I said before it's probably not important
> 
>     5. And in Steam I already had WINEDLLOVERRIDES="dsound=n,b" %command%
> 
> 
> Thank you so much for your help!

@StealthRook good that you found a solution! Just a heads-up that some of those steps are actually redundant. For step 1, just downloading the [latest release](https://github.com/kcat/dsoal/releases/tag/latest-master) is enough; I'm not sure what *EAX Unified* would be needed for here. Also, installing `dsoal` using `winetricks` (step 3) is redundant if you already did step 1. And for step 4, either using @ThreeDeeJay's patch or my .reg script is enough (no need for both).

**Comment by mirh** [comment]
EAX unified shouldn't be needed, yeah.. without it IIRC normal dsound loading procedure happens.
Btw in wine it seems stupid to use setacl (and also to take backups). You could probably just have directly the "reg add" loop.

p.s. the script is also broken in the part where it checks for the architecture of the cpu rather than the [bitness](https://ss64.com/nt/syntax-64bit.html) of the OS. Besides on arm (I wonder what would happen on the rare armv7 [build](https://www.betaarchive.com/forum/viewtopic.php?t=40522)?), it could also return [differently](https://github.com/wine-mirror/wine/blob/wine-11.3/programs/wineboot/wineboot.c#L702) on amd cpus.

**Comment by mthsk** [comment]
Using the registry hack I was able to get EAX working on GTA Vice City and Gears of War, but I had issues with F.E.A.R. and its SndDrv.dll

Until I found out about [EchoPatch](https://github.com/Wemino/EchoPatch) which solved all of my issues and was much easier to set up.

**Comment by ThreeDeeJay** [comment]
Dang, I must've missed those previous notifications.
But anyway, thanks for confirming my PR works.
I went ahead and merged it and uploaded a [new release](https://github.com/ThreeDeeJay/DSWRP/releases/tag/v1.4.0).
But feel free to submit a PR with any further fixes. 👌 

Oh, and I also added the EchoPatch tip to the [database](https://airtable.com/appayGNkn3nSuXkaz/shrZP6E5xqQjsvplj?eCzZW=recXQtj2ITta1vW1U). 👍

**Comment by mirh** [comment]
GoW is a UE3 game, you want to use openal directly with it.
https://github.com/Wemino/EchoPatch/commit/f7cc3118bb41cc5aa8cdd1a09e7f4181f2c026c7 is interesting, even though I believe they implemented it just because they didn't understand HKLM.

And last but not least, to all our wine friends I [believe](https://gitlab.winehq.org/wine/wine/-/merge_requests/6527) that since 11.6 you shouldn't need any more override to get dsoal working (I mean the wine dlls ones, DSWRP is still required).
p.s. fun fact: the normal dsound that they use [doesn't](https://gitlab.winehq.org/wine/wine/-/merge_requests/10557) even support 7.1
