### ISSUE TITLE
No surround in Dishonored (Steam Proton)

### ISSUE THREAD

**Issue by mrmatteastwood** [kcat/dsoal#68]
Here's another one. I posted on the Proton GitHub about this as well:
https://github.com/ValveSoftware/Proton/issues/51#issuecomment-1213104231

The Proton log shows that the game runs dsound.dll from the system32 directory. So perhaps there's something to be done here with DSOAL? I tried:

- putting the 32-bit dsound.dll and dsoal-aldrv.dll into the game's Binaries\Win32 directory, where Dishonored.exe lives
- replacing the dsound.dll in system32 with DSOAL's dsound.dll while keeping dsoal-aldrv.dll in the game's Binaries\Win32 directory, Binaries directory and root directory for good measure.

I then ran the game from Lutris using Lutris' "Disable Lutris runtime" and "Prefer System libraries" options.

So far, no luck.

**Comment by mirh** [comment]
Dishonored uses wwise.

**Comment by mrmatteastwood** [comment]
I read the same thing, but then I was surprised when it was loading dsound.dll from system32. I guess dsound.dll just gets loaded either way?

**Comment by kcat** [comment]
system32 is for 64-bit DLLs, syswow64 is for 32-bit DLLs. I'd expect Dishonored to be a 64-bit game, so it would be loading the 64-bit DLL from system32.

The game/wwise could be loading dsound.dll as a backup in case wasapi playback fails, or if they're using a 3rd party video playing library that uses dsound for output separate from the main game. Or  if it uses something like DirectShow that loads an optional dsound output sink.

**Comment by mirh** [comment]
Game uses bink, so that could be it. 
It's 32-bit though.

**Comment by mrmatteastwood** [comment]
Okay, that explains things. Thanks! Let's see if the Proton team can come up with something for this one.

**Comment by mirh** [comment]
Well, screw me. It might still be that bink uses directsound (I don't really know how to tell when an api is *actually* active), but I can most definitively confirm that it is the wwise code inside the game executable to be loading it. 
XAudio2 isn't used at all then, but it would still seem pretty strange if 2010~2012 still didn't eventually use WASAPI at least (which they do load too, and that could easily explain why 5.1 should was already working out of the box without a hitch). 

As for the problem in this thread.. my (un)educate guess is that it was system specific. 
https://github.com/ValveSoftware/Proton/issues/6138
I checked the last months of proton commits and mint release notes, with no evidence of anything new sound-related.

**Comment by mrmatteastwood** [comment]
Hmm, quite odd indeed! I can confirm that the last time I checked surround sound in Dishonored, it was after installing Linux Mint 21.1 on my system in early December. I remember it didn't work before then, so yeah, it might have been something on my previous system config. Either way, just to confirm in this thread as well: Surround sound in Dishonored works on my current Linux Mint 21.1 setup. Still the same PC.

**Comment by mirh** [comment]
Well, you can try to force older proton branches to immediately see who's the culprit.

**Comment by mrmatteastwood** [comment]
I checked and can confirm that on my current setup, surround works even on an old Proton version (5.13). However, it only works when picking the "Digital Surround 5.1" output profile. When choosing 7.1, the game plays in stereo.

**Comment by mirh** [comment]
I just checked with my xonar on W10, and everything was actually just fine with 7.1. 
(I mean, the game was still limited to just 6 channels, and directionality may be slightly compromised given that "back left" and "back right" aren't angled in the same positions of  "side left" and "side right" in 5.1, but still it wasn't just stereo). 

So I guess you would still have a bug there to report.
