### ISSUE TITLE
DSOAL has no DS3D with the builds I compile

### ISSUE THREAD

**Issue by BEENNath58** [kcat/dsoal#74]
I downloaded the DSOAL source and used CMake 3.25.1 + VC++2022 to build it. I kept the Build Type, Config Prefix and Install Prefix to their default settings. After building and using the dsound.dll file (along with renamed, dsoal-aldrv.dll from OpenAL Soft) as well as the .ini file from an older build, I still don't get any option to utilise the DirectSound3D capabilities in games.

GTA Vice City and III (with the patched mss32.dll) would have DS3D and EAX available with the older, already built DSOAL versions but it wouldn't detect on mine. I might be doing something wrong. Can I be helped?

**Comment by kcat** [comment]
A log output would be helpful. Set the `DSOAL_LOGLEVEL` environment variable to `3`, and `DSOAL_LOGFILE` to a full path+filename. Then when you run the app, it'll write the log to the named file. If it doesn't produce a log, it's not using DSOAL's `dsound.dll`, but if it does, attach it here and it may shed light on what's wrong.

One thing to watch for, is to make sure you're building for the right architecture. If GTA3/VC is 32-bit, then both DSOAL's `dsound.dll` and `dsoal-aldrv.dll` need to be 32-bit. Or if the game's 64-bit, those DLLs need to be 64-bit also.

**Comment by BEENNath58** [comment]
I was just about to tell about the architecture thing. I tried a game Motorhead that apparently supports A3D, and it gave an architecture mismatch message.

Turns out CMake changed the architecture to x64 while VC had it on Win32 by default, so turning the CMake setting to Win32 fixed it. And now I can get the DS3D support. The problem is fixed.
