### ISSUE TITLE
Assassin's Creed 1 (Director's Cut) - no reverb

### ISSUE THREAD

**Issue by Lrflx** [kcat/dsoal#84]
Here's video with how it supposed to sound (not mine, but can confirm it's the same on my side with Alchemy): https://www.youtube.com/watch?v=7n1ljheTeGM
Like here at this point https://youtu.be/7n1ljheTeGM?t=196 voices have reverb and with DSOAL it's completely absent. Reverb boost doesn't seem to do anything.
Though I do understand it's eax 4.0, so it might not be implemented at all with that version yet, but I didn't find any standing issues and decided to report it cause it might be an actual problem.

**Comment by kcat** [comment]
EAX 4 should work, though since fewer games use it, it doesn't have as much testing. Are you able to provide DSOAL and OpenAL Soft logs? You should be able to make them by creating a batch file (named something like `debug-dsoal.bat`) with:
```
set DSOAL_LOGLEVEL=3
set DSOAL_LOGFILE=dsoal.log
set ALSOFT_LOGLEVEL=3
set ALSOFT_LOGFILE=alsoft.log
<name of app>.exe
```
Place that in the same directory as the game's executable, and replace `<name of app>` with the actual executable name. Run that and load into a place that you know should have reverb, and it'll create `dsoal.log` and `alsoft.log` files that you can provide here (may need to zip them together), which should help show what's going on.

**Comment by kcat** [comment]
It seems the issue is this:
```
2528:trace:dsound:DSBufferProp_QuerySupport (0AB52124)->(EAXPROPERTYID_EAX40_FXSlot0, 0x1, 0019F820)
2528:fixme:dsound:EAX4Slot_Query Unhandled effect propid: 0x00000001
```
After that query failure, it stops doing anything with EAX. I guess this means querying the effect properties themselves from FXSlots should work, rather than just the FXSlot properties. Commit 490497f56acdfcc2c65575c78fe8dc26c2d42d05 should fix that.

**Comment by Lrflx** [comment]
I did some more testing and I might be in the wrong actually, or at least I found something puzzling. Tried compiling a new version and didn't hear any difference with it, even got similar fixme line in the log. But then I noticed I was in audio creation mode all this time and openal and alchemy were working through software purely. So I set everything back to game mode and AC started to sound pretty much the same as with dsoal.
So I don't know, does that mean software alchemy just adds reverb where it shoudn't? Though reverb wasn't just everywhere in software, only inside buildings. Or there's actually some bug in audio engine which is being resolved only in software mode.

**Comment by kcat** [comment]
I missed something for that commit, preventing it from actually doing anything. It should behave more properly now with commit 52224b17832fda41d02153cf8f56d27cd94bf79a.

I don't know what the deal is with Audio Creation Mode vs Game Mode with ALchemy and hardware OpenAL, but getting updated logs with a new build of DSOAL should show more of what the game's trying to do.

**Comment by Lrflx** [comment]
It works now! And better than oldschool hardware alchemy it seems. Though I guess it's not surprising cause it wasn't properly maintained since Win7 times and currently it's very unreliable.
Original issue could be closed, but I wanted to check for one last thing if I can. This game has another bug when some sounds start to move between channels very fast in some circumstances, maybe it's an engine bug and can't be fixed that easily, but I tried to capture one of those moments in logs, do they have any anomalies visible there?
[AC_logs2.zip](https://github.com/kcat/dsoal/files/11162236/AC_logs2.zip)

**Comment by kcat** [comment]
Nothing stands out in the buffers' `SetPosition` calls I'm looking at, but it's not particularly easy to track individual sounds over time. The listener properties are also being set with the `SetAllParameters` function, which doesn't show the individual parameters.

Does it affect all or many sounds at the same time? Or just a few at different times? And does it happen with hardware/ALchemy too?

**Comment by Lrflx** [comment]
Yes, it does happen with alchemy also, both hardware and software. I think only some ambient tracks are affected, something to do with broken positioning I guess. And there're no problems at all when sound enhancements disabled completely, does look like game implementation of eax itself is bugged.
Probably can't be fixed without getting into the game's code first.
Anyway, thanks for saving another game from eax limbo!
