### ISSUE TITLE
Baldur's Gate II (classic) crashes on quit

### ISSUE THREAD

**Issue by Hexaae** [kcat/dsoal#87]
Baldur's Gate II Shadows of Amn

Latest NON-crashing build on quit was dsoal-r430.7z
from http://vaporeon.io/hosted/dsoal-builds/

**Comment by ThreeDeeJay** [comment]
Might wanna provide a log to help debug it.
You can [set environment variables](https://github.com/kcat/dsoal#environment-variables) to enable it or just drag and drop the game exe into [the bat file here](https://github.com/kcat/dsoal/files/11360875/DSOAL%2BALSOFT_log.zip).

**Comment by Hexaae** [comment]
Thank you for the BAT file, will use in future reports in case.
Just tested latest build:
dsoal-r444.7z	2023-Apr-17 06:14:07	786.1K
and it doesn't crash anymore on quit! 👍🏻

**Comment by ThreeDeeJay** [comment]
Also for future reference, you could try the build from my fork, which rebuilds every day so it always has a recent/latest OpenAL Soft in case bugs are fixed on that end: https://github.com/ThreeDeeJay/dsoal/releases/tag/latest
Just keep in mind the r### represents the commit count on my fork which is slightly higher than the main one, but it's still using the latest main DSOAL repo as base, plus my changes which are just for Github automation, no changes on DSOAL code itself.
