### ISSUE TITLE
64 bit version in MSVC 2019

### ISSUE THREAD

**Issue by donizettilorenzo** [kcat/dsoal#9]
Creating an x86-Release configuration -> build success
Using default x64-Debug configuration -> Linking errors

**Comment by mirh** [comment]
It must have something to do with #2 (because those are all the problematic symbols), which I can't quite put my finger on though.

**Comment by kcat** [comment]
How many 64-bit apps actually use DSound3D? IIRC, 64-bit XP wasn't widely used, and Vista dropped accelerated DSound when 64-bit Windows started gaining traction. I haven't really been mindful of 64-bit support since I'm not sure there's that much use for it (though if there's a desire for it, any help in making it work would be appreciated).

Either way, seeing the errors would be helpful in figuring out the problem you're having.

**Comment by mikfhan** [comment]
If it helps, I got these errors from Visual Studio 2017 build of x64 Release dsound.dll:

2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCaptureCreate@12
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCaptureCreate8@12
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCaptureEnumerateA@8
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCaptureEnumerateW@8
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCreate@12
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundCreate8@12
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundEnumerateA@8
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundEnumerateW@8
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DirectSoundFullDuplexCreate@40
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DllCanUnloadNow@0
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_DllGetClassObject@12
2>dsound.exp : error LNK2001: unresolved external symbol _DSOAL_GetDeviceID@8

**Comment by mirh** [comment]
64-bit programs definitively weren't a thing at least until after 2010. 
This said, it may have been possible for some "early tech demo" (I'm thinking to far cry or crysis [for example](https://www.start64.com/index.php/64-bit-news/old-articles/190-the-list-of-64-bit-games)) to still have kept *baked* both things at once.

**Comment by NTULINUX** [comment]
Creating an x86-Release configuration -> build success
Using default x64-Debug configuration -> Linking errors

What about an x86-Debug configuration?

**Comment by phobos2077** [comment]
I'd be great to have 64 bit binaries of this. Want to use it with 64-bit Crysis binaries.

**Comment by kcat** [comment]
> If it helps, I got these errors from Visual Studio 2017 build of x64 Release dsound.dll

Hmm. If you edit msvc.def and remove the underscore from `_DSOAL` (so you end up with `DSOAL_DirectSoundCreate@12`, `DSOAL_DirectSoundEnumerateA@8`, etc), does it work then?

**Comment by NTULINUX** [comment]
> 
> 
> I'd be great to have 64 bit binaries of this. Want to use it with 64-bit Crysis binaries.

Are you running into problems building it, or do you just want the files hosted?

**Comment by kcat** [comment]
With the latest commits, I've been able to build a 64-bit version with MinGW, though I haven't tested it. For 64-bit MSVC, I guess it dresses the symbols differently from 32-bit, forgoing either the preceding `_`, or the `@N` signifying the parameter stack size, or both, requiring changes to `msvc.def`.

**Comment by NTULINUX** [comment]
@mirh you're confused by my question, and I'm confused by his statement..

**Comment by phobos2077** [comment]
> Are you running into problems building it, or do you just want the files hosted?

I'm just a passer-by interested in using this library with 64-bit games. I see now this repository doesn't have any releases. Don't remember where I actually downloaded them (probably from nexus or pcgamingwiki), but it'd be great if someone managed to compile this to work with 64-bit versions of games.

**Comment by donizettilorenzo** [comment]
MSVC 2019 -> still impossible to build (symbol issue as suggested)
Please, upload/attach the binaries created via MinGW !

Il giorno mar 21 gen 2020 alle ore 18:04 Vlad <notifications@github.com> ha
scritto:

**Comment by NTULINUX** [comment]
> 
> 
> > Are you running into problems building it, or do you just want the files hosted?
> 
> I'm just a passer-by interested in using this library with 64-bit games. I see now this repository doesn't have any releases. Don't remember where I actually downloaded them (probably from nexus or pcgamingwiki), but it'd be great if someone managed to compile this to work with 64-bit versions of games.

Got it. Nexus has DSOAL on their website, last updated June 2019. I have 32-bit binaries, and once 64-bit builds, I'll host them as well. Not everyone has Visual Studio on their PCs and compiling for Windows isn't quite as easy as Linux IMO.. Open terminal, run make, done lol.

**Comment by kcat** [comment]
It's now building with 64-bit MSVC 2017 with commit 307fd857ea42101b124ecb7d899ffc32bf79c083. I assume it'll work with 2019 too. If there's still issues there, let me know and I'll reopen this.

Regarding binaries, I'm working on getting appveyor to produce build artifacts so you'll be able to get prebuilt DLLs from there when that's done. See issue #13.

**Comment by donizettilorenzo** [comment]
Thanks man! MUCH appreciated!

Il giorno dom 1 mar 2020 alle ore 00:59 kcat <notifications@github.com> ha
scritto:

**Comment by jeremywh7** [comment]
Fwiw, I built the x64 dsound.dll per @Galenmacil using VS2019 IDE with cmake (ninja).  I thought I would try this with Far Cry x64, which already had working 5.1 audio (by default, without DSOAL).  Audio does work (with soft_oal.dll 1.21.1 renamed to dsoal-aldrv.dll) but only in stereo.  This is with or without using an alsoft.ini and .ambdec file (that have worked before on x86 games).  Any ideas?  I've attached my x64 dsound in case someone wants to try it.
[DSOAL x64-release dsound.dllf2d74d7 (25oct2020).zip](https://github.com/kcat/dsoal/files/5974923/DSOAL.x64-release.dsound.dllf2d74d7.25oct2020.zip)

**Comment by donizettilorenzo** [comment]
OpenAL Soft doesn't use Center and LFE, so you get 4 channels (and EAX).

Il giorno sab 13 feb 2021 alle ore 02:27 jeremywh7 <notifications@github.com>
ha scritto:

**Comment by kcat** [comment]
OpenAL Soft doesn't mix to center or LFE for spatialization, by default, no. It does use the surround speakers and isn't just stereo, though. If OpenAL Soft's picking just stereo, that would be because the device is either being reported as stereo, or has a weird configuration where stereo is the only recognizable speakers it can use. I'd have to see a log output from OpenAL Soft to see what it's doing.

However, if the same code was used to build 64-bit and 32-bit DLLs, and the 64-bit game is behaving differently from the 32-bit one on the same system, it would likely be the app behaving differently. I don't think 64-bit Windows ever had accelerated DSound, so perhaps DSOAL is reporting something that confuses the 64-bit app that makes it fall back to simple stereo output.

**Comment by donizettilorenzo** [comment]
It's working on my system: https://postimg.cc/YhbPh6s4

**Comment by jeremywh7** [comment]
Thanks for the replies!  :-)

> It's working on my system

Do you get positional audio though?  I do actually get a little ambient sound in the rear speakers (tested in a helicopter scene), but it's not positional like it is with the in-game default; there's none of the helicopter sound in fact, just the ambient 'nature' sounds.  Interestingly, I tried testing surf sounds near a shoreline and it was -not- directional... in neither in-game default nor dsoal+openal-soft.  So it does seem like there is something weird going on.  But the helicopter is a clear difference between them.  Using alsoft.ini with an .ambdec file made no difference either, which I have used in 32-bit bit games to get the center channel working.  At some point, I'll also try testing Far Cry 32-bit to see if any of this behavior is different.

> I'd have to see a log output from OpenAL Soft to see what it's doing.

So, to get logging it looks like I just set the "ALSOFT_LOGLEVEL=3" user (or system?) env var (per /docs/env-vars.txt), and I'll get a default name in the .exe. dir?  Or do I also need to set "ALSOFT_LOGFILE" to something?

**Comment by donizettilorenzo** [comment]
Where did you take from the ambdec file? Eager to test myself!

**Comment by jeremywh7** [comment]
I use the itu5.1-ambdec from the OpenAL Soft release's preset folder (also in the git repo).  :-)  Meant to ask you... what tool did you use to capture the per-channel audio in your screenshot above?

**Comment by donizettilorenzo** [comment]
MSI Afterburner controlling RTSS for the video+audio grabbing -> audio extraction via MKVToolNix+MKVCleaver -> Ocenaudio Audio Editor

**Comment by jeremywh7** [comment]
Ok @kcat I got a log (settings both aforementioned env var's as _system_). [alsoft.zip](https://github.com/kcat/dsoal/files/5978745/alsoft.zip)
I tried running at both 48000 and 44100 Hz with no difference.  Not that this matters for the original positional audio issue, but I noticed these initially:
```
[ALSOFT] (II) Found decoder/surround51 = "itu5.1.ambdec"
[ALSOFT] (EE) Failed to load layout file itu5.1.ambdec
[ALSOFT] (EE)   Failed to open file
```
I was using a relative path which has worked in the native openAL 32-bit games I've tested, but not here.  Anyway, with an absolute path the center channel starts working, but still no directional audio to the rear speakers.  Both logs are zipped. Thanks!

**Comment by mirh** [comment]
You can also use [audacity](https://community.pcgamingwiki.com/topic/804-analyzing-the-game-executables-for-audio-channels/#comment-4668).

**Comment by donizettilorenzo** [comment]
Far Cry 64 (Upscaled Mod), DSOAL (from the master tree)+OpenAL Soft 1.21.1+itu5.1.ambdec+5.1+EAX -> https://postimg.cc/vD30DzDJ

Center channel is working.

**Comment by jeremywh7** [comment]
> Center channel is working.

Do you get positional audio from your rear speakers with non-ambient sound sources?

@kcat  Did you have a change to see if my logs were any help?  Thanks!
