### ISSUE TITLE
Rewrite build fails on GitHub actions

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/dsoal#98]
I cloned the [c++ rewrite branch](https://github.com/kcat/dsoal/tree/c%2B%2B-rewrite) to try setting up [daily builds](https://github.com/ThreeDeeJay/dsoal/releases/tag/latest) like PR #52 but I'm getting [compilation errors](https://github.com/ThreeDeeJay/dsoal/actions/runs/6891365161/job/18746269131#step:6:59).
Initially I though it was because the project was [targeting Visual Studio 2017](https://github.com/kcat/dsoal/blob/611413973d6eabe547d13ed73311f9cd182924eb/appveyor.yml#L4) which works on Appveyor, but the master branch also [targets VS 2017](https://github.com/kcat/dsoal/blob/52224b17832fda41d02153cf8f56d27cd94bf79a/appveyor.yml#L4) and [builds fine with VS 2022](https://github.com/ThreeDeeJay/dsoal/actions/runs/7269380136/job/19806915235#step:6:13). I also tried using the oldest runner available on Github actions (VS 2019), but [it still failed, even with more compilation errors](https://github.com/ThreeDeeJay/dsoal/actions/runs/6891405306/job/18746391590#step:6:69). So any idea why it's failing?

Also, would you recommend using it as a replacement for the master branch? or are there any major features missing?🤔
I'm planning to record and upload a full Prince of Persia: The Two Thrones playthough soon™️, so I figured maybe I could try the rewrite to see if I can spot any issues, so it'd come in handy to know what to look for 👀👌

**Comment by kcat** [comment]
The compilation errors seem to be from a missing `<string>` include in `propset.cpp`.

`DSSCL_WRITEPRIMARY`, Capture, and FullDuplex aren't working/implemented currently. Some of the `DirectSoundPrivate` interface is also not all there. Many things should work though, so it's definitely worth trying out.

**Comment by UserGit-2021** [comment]
> The compilation errors seem to be from a missing `<string>` include in `propset.cpp`.
> 
> `DSSCL_WRITEPRIMARY`, Capture, and FullDuplex aren't working/implemented currently. Some of the `DirectSoundPrivate` interface is also not all there. Many things should work though, so it's definitely worth trying out.

Should we expect a DSOAL update in the near future? There has been no update for a long time, 10 months have passed.

**Comment by mirh** [comment]
Atm work is flying like there's no tomorrow on openal-soft
So... delighted as I may also be to see this getting progress, let's not disturb the brisk development focus

**Comment by ThreeDeeJay** [comment]
Looks like [one of the recent commits](https://github.com/kcat/dsoal/compare/master...c%2B%2B-rewrite) fixed this because GitHub actions builds of the rewrite branch are [magically succeeding](https://github.com/ThreeDeeJay/dsoal/actions?query=branch%3Ac%2B%2B-rewrite) now so I'll go ahead and close this issue 👀👌 
https://github.com/ThreeDeeJay/dsoal/releases/tag/latest-c%2B%2B-rewrite
https://github.com/ThreeDeeJay/dsoal/releases/download/latest-c%2B%2B-rewrite/DSOAL.zip
https://github.com/ThreeDeeJay/dsoal/releases/download/latest-c%2B%2B-rewrite/DSOAL+HRTF.zip
